#!/bin/bash

# Set the source file and binary name
SRC="A2.c"
BINARY="./a.out"

# Compile the C file with debug symbols
gcc -m32 -g -z execstack -fno-stack-protector "$SRC"

# Extract the base pointer (ebp for 32-bit binary)
gdb -ex "set environment _=$(pwd)/a.out" -ex "unset environment LINES" -ex "unset environment COLUMNS" -ex "break bof" -ex "run" "$BINARY"
